// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSnapshot: () => __TAURI_INVOKE<Snapshot>("get_snapshot"),
	addList: (name: string) => __TAURI_INVOKE<Snapshot>("add_list", { name }),
	renameList: (id: string, name: string) => __TAURI_INVOKE<Snapshot>("rename_list", { id, name }),
	setListStyle: (id: string, emoji: string, color: string) => __TAURI_INVOKE<Snapshot>("set_list_style", { id, emoji, color }),
	setListLifeTag: (id: string, area: string | null, direction: string | null) => __TAURI_INVOKE<Snapshot>("set_list_life_tag", { id, area, direction }),
	setListAvailability: (id: string, windows: WeeklyTimeWindow[]) => __TAURI_INVOKE<Snapshot>("set_list_availability", { id, windows }),
	reorderLists: (orderedIds: string[]) => __TAURI_INVOKE<Snapshot>("reorder_lists", { orderedIds }),
	reorderLifeAreas: (orderedAreaKeys: string[]) => __TAURI_INVOKE<Snapshot>("reorder_life_areas", { orderedAreaKeys }),
	deleteList: (id: string) => __TAURI_INVOKE<Snapshot>("delete_list", { id }),
	addTask: (listId: string, name: string, estimateMin: number | null) => __TAURI_INVOKE<Snapshot>("add_task", { listId, name, estimateMin }),
	renameTask: (id: string, name: string) => __TAURI_INVOKE<Snapshot>("rename_task", { id, name }),
	setDepth: (id: string, depth: string | null) => __TAURI_INVOKE<Snapshot>("set_depth", { id, depth }),
	setCadence: (id: string, cadence: string | null) => __TAURI_INVOKE<Snapshot>("set_cadence", { id, cadence }),
	setDailyWindows: (id: string, windows: WeeklyTimeWindow[]) => __TAURI_INVOKE<Snapshot>("set_daily_windows", { id, windows }),
	setSessionRange: (id: string, minMinutes: number | null, maxMinutes: number | null) => __TAURI_INVOKE<Snapshot>("set_session_range", { id, minMinutes, maxMinutes }),
	setEstimate: (id: string, minutes: number | null) => __TAURI_INVOKE<Snapshot>("set_estimate", { id, minutes }),
	setDeadline: (id: string, deadlineAt: number | null) => __TAURI_INVOKE<Snapshot>("set_deadline", { id, deadlineAt }),
	setTaskImpact: (id: string, tier: string | null, sign: number) => __TAURI_INVOKE<Snapshot>("set_task_impact", { id, tier, sign }),
	setDone: (id: string) => __TAURI_INVOKE<Snapshot>("set_done", { id }),
	setDescription: (id: string, text: string | null) => __TAURI_INVOKE<Snapshot>("set_description", { id, text }),
	setAlbum: (id: string, album: string | null) => __TAURI_INVOKE<Snapshot>("set_album", { id, album }),
	moveTask: (id: string, listId: string) => __TAURI_INVOKE<Snapshot>("move_task", { id, listId }),
	reorderTasks: (listId: string, orderedIds: string[]) => __TAURI_INVOKE<Snapshot>("reorder_tasks", { listId, orderedIds }),
	deleteTask: (id: string) => __TAURI_INVOKE<Snapshot>("delete_task", { id }),
	addSession: (taskId: string, start: number | null, end: number | null) => __TAURI_INVOKE<Snapshot>("add_session", { taskId, start, end }),
	updateSession: (id: string, start: number | null, end: number | null) => __TAURI_INVOKE<Snapshot>("update_session", { id, start, end }),
	deleteSession: (id: string) => __TAURI_INVOKE<Snapshot>("delete_session", { id }),
	/**
	 *  Serialize all data to a JSON backup in ~/Downloads and reveal it in Finder.
	 *  Returns the written file path.
	 */
	exportData: () => typedError<string, string>(__TAURI_INVOKE("export_data")),
	/**
	 *  Reveals `taskplayer.log` in Finder (creating an empty one first if
	 *  nothing's been logged yet), the same "open -R" pattern export_data uses —
	 *  so "attach your logs to a bug report" is a single click in Settings
	 *  instead of "go find ~/Library/Logs yourself." Returns the path so the
	 *  frontend can show it, in case Finder itself doesn't grab focus.
	 */
	revealLogs: () => typedError<string, string>(__TAURI_INVOKE("reveal_logs")),
	/**
	 *  Replace all data from a backup JSON string. Clears the run state so nothing
	 *  is left "playing" against tasks that may no longer exist.
	 */
	importData: (payload: string) => typedError<Snapshot, string>(__TAURI_INVOKE("import_data", { payload })),
	play: (taskId: string) => __TAURI_INVOKE<Snapshot>("play", { taskId }),
	stop: () => __TAURI_INVOKE<Snapshot>("stop"),
	skipBreak: () => __TAURI_INVOKE<Snapshot>("skip_break"),
	/**
	 *  Backward-compatible recovery for an `awaiting_break` state written by app
	 *  versions that paused at Pomodoro boundaries. New cycles start breaks in
	 *  `timer::tick` and never need this command.
	 */
	startBreak: () => __TAURI_INVOKE<Snapshot>("start_break"),
	/**
	 *  Backward-compatible recovery for an `awaiting_work` state written by app
	 *  versions that paused at Pomodoro boundaries. New cycles resume work in
	 *  `timer::tick`; `skip_break` remains the normal early-break action.
	 */
	resumeWork: () => __TAURI_INVOKE<Snapshot>("resume_work"),
	setMode: (mode: string) => __TAURI_INVOKE<Snapshot>("set_mode", { mode }),
	/**
	 *  Device-local interface zoom. The frontend keeps the selected step in
	 *  localStorage; this clamp is the final boundary so no caller can push the
	 *  app below 80% or above 130%.
	 */
	setAppZoom: (scale: number | null) => typedError<null, string>(__TAURI_INVOKE("set_app_zoom", { scale })),
	setConfigField: (key: string, value: number) => __TAURI_INVOKE<Snapshot>("set_config_field", { key, value }),
	/**
	 *  Same shape as `set_config_field`, split out because the two sound pickers
	 *  are string-valued (a system sound name) rather than the clamped integers
	 *  every other pomodoro setting uses. Falls back silently to the existing
	 *  value for anything not in `SOUND_OPTIONS` — the picker only ever sends one
	 *  of those, so this only guards against a stale/tampered frontend value.
	 */
	setConfigSound: (key: string, value: string) => __TAURI_INVOKE<Snapshot>("set_config_sound", { key, value }),
	/**
	 *  Curated set of classic macOS system sound names — these ship with every
	 *  Mac (`/System/Library/Sounds/*.aiff`) and are what `NotificationBuilder::sound`
	 *  resolves by name, so there's nothing to bundle. Shared with the frontend via
	 *  `sound_options()` so the Settings picker can never drift out of sync with
	 *  what the backend actually accepts.
	 */
	soundOptions: () => __TAURI_INVOKE<string[]>("sound_options"),
	/**
	 *  Opens the system browser to Google's consent screen and returns
	 *  immediately — the deep-link callback (registered in `setup()`) drives
	 *  the rest of the flow asynchronously and calls `push()` once signed in.
	 */
	signInGoogle: () => typedError<null, string>(__TAURI_INVOKE("sign_in_google")),
	signOut: () => __TAURI_INVOKE<Snapshot>("sign_out"),
	/**
	 *  Fire-and-forget, like `sign_in_google` — the eventual `push()`/`refresh()`
	 *  inside `run_sync` notifies the frontend once the sync finishes.
	 */
	syncNow: () => __TAURI_INVOKE<void>("sync_now"),
	/**
	 *  Escape hatch for exactly the "other device's row never showed up" case —
	 *  see `reset_sync_cursors`.
	 */
	fullSync: () => __TAURI_INVOKE<void>("full_sync"),
	openMain: () => __TAURI_INVOKE<void>("open_main"),
	/**
	 *  Mirrors the focus-music widget's play/pause state into Rust purely so the
	 *  tray's music toggle can show the right label — the actual `<audio>`
	 *  element lives in the webview (music.js), Rust never touches it directly.
	 *  The frontend calls this every time window.Music's own state changes.
	 */
	setMusicPlaying: (playing: boolean) => __TAURI_INVOKE<Snapshot>("set_music_playing", { playing }),
	toggleMusicFavorite: (track: MusicFavoriteInput) => __TAURI_INVOKE<Snapshot>("toggle_music_favorite", { track }),
	/**
	 *  One-time bridge from the localStorage implementation. Existing SQLite
	 *  rows, including tombstones synced from another device, always win so an
	 *  old browser cache cannot resurrect a deliberately removed favorite.
	 */
	importMusicFavorites: (tracks: MusicFavoriteInput[]) => __TAURI_INVOKE<Snapshot>("import_music_favorites", { tracks }),
	/**
	 *  Opens a URL in the system's default browser — used by the in-app "View on
	 *  Audius" button (a plain `<a href>` would just navigate the app's own
	 *  webview away instead).
	 */
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	/**
	 *  Asks the configured endpoint (Casks/taskplayer.rb's own GitHub Releases —
	 *  see `scripts/release.sh`) whether a newer signed build exists. Stashes the
	 *  `Update` handle (it carries the download URL + signature) in `AppState`
	 *  so `install_update` doesn't have to re-check; the frontend only ever
	 *  sees the plain version/notes, never the handle itself.
	 */
	checkForUpdate: () => typedError<{
	version: string,
	notes: string | null,
} | null, string>(__TAURI_INVOKE("check_for_update")),
	/**
	 *  Downloads + installs whatever `check_for_update` last found, then
	 *  restarts. Errors (network drop mid-download, signature mismatch, disk
	 *  full) surface to the Settings page instead of leaving the app in a half
	 *  -updated state; nothing here touches the user's data — `AppState`'s SQLite
	 *  handle is untouched by the app-bundle swap, which is the whole point of
	 *  updating the .app rather than reinstalling.
	 */
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
};

/* Types */
/**
 *  Signed-in Google/Supabase profile. Durable, rarely-changing state — lives
 *  in `Snapshot` alongside `config`/`run`, not in the ephemeral `Status` tick.
 */
export type AccountInfo = {
	id: string,
	email: string,
	name: string | null,
	avatarUrl: string | null,
};

/**
 *  User-controlled planning precedence for one fixed life area. Rank 1 is
 *  highest. The area name/color remain defined by the app; only this order is
 *  persisted and synced.
 */
export type LifeAreaPriority = {
	areaKey: string,
	priorityRank: number,
	updatedAt: number | null,
};

/**
 *  A saved focus-music track. The complete playback metadata is stored so a
 *  favorite remains playable without re-running an Audius search on another
 *  device. Deletes are tombstoned for cross-device propagation.
 */
export type MusicFavorite = {
	trackId: string,
	title: string,
	artist: string,
	artworkUrls?: string[],
	permalink: string | null,
	sourceType: string,
	updatedAt: number | null,
};

/**
 *  Frontend payload for saving/importing a track; sync timestamps are always
 *  assigned by the database boundary rather than accepted from the webview.
 */
export type MusicFavoriteInput = {
	trackId: string,
	title: string,
	artist: string,
	artworkUrls?: string[],
	permalink: string | null,
	sourceType: string,
};

export type RunState = {
	activeTaskId: string | null,
	runningStart: number | null,
	/**  "work" | "break" | null */
	phase: string | null,
	breakStart: number | null,
	/**
	 *  Last task that was playing — remembered after stop so the player can
	 *  keep showing it and resume (Spotify-style). Mirrors active_task_id while
	 *  running; retained when stopped. `#[serde(default)]` keeps old saved
	 *  run-state JSON (without this field) deserializable.
	 */
	lastTaskId?: string | null,
	/**
	 *  Completed work cycles (full pomodoro work blocks) since the last long
	 *  break. Incremented by `timer::tick` each time a work block finishes;
	 *  reset to 0 the moment that count reaches `cycles_before_long_break` —
	 *  i.e. it resets as soon as the automatically-started long break is
	 *  earned. Stopping/resuming the timer never touches this counter — only
	 *  a work block that runs to completion does. `#[serde(default)]` keeps
	 *  old saved run-state JSON deserializable.
	 */
	cyclesCompleted?: number,
	/**
	 *  True while `phase` is "break" and that break is the long one. Set by
	 *  `timer::tick` when the cycle threshold is hit and cleared once the
	 *  break ends or the timer takes another transition. Older synced states
	 *  may still contain `awaiting_break`; `start_break` preserves the flag
	 *  while recovering them. `#[serde(default)]` keeps old JSON readable.
	 */
	longBreak?: boolean,
	/**
	 *  Which device currently owns this session, for cross-device sync (see
	 *  docs/session-sync-design.md) — `Db::get_device_id()`'s stable
	 *  per-install id, stamped by `main.rs` (never by `timer.rs`, which stays
	 *  pure I/O-free) on every local play/stop/phase-transition. `None` means
	 *  either a pre-migration local-only RunState or a fresh reset (e.g.
	 *  `import_data`) — treated as "this device's own" by the reconciliation
	 *  logic in `main.rs`, never as a foreign session. `#[serde(default)]`
	 *  keeps old saved run-state JSON deserializable.
	 */
	deviceId?: string | null,
	/**
	 *  Best-effort display name for `device_id` ("MacBook Pro") — purely for
	 *  the "Playing on ..." UI treatment, never compared/used for any sync
	 *  logic. `#[serde(default)]` keeps old saved run-state JSON
	 *  deserializable.
	 */
	deviceName?: string | null,
	/**
	 *  ms epoch this RunState was last changed BY ITS OWNING DEVICE — drives
	 *  cross-device sync (last-write-wins), same convention as
	 *  `TaskList`/`Task`/`Session`'s `updated_at`. NOT touched by pure
	 *  wall-clock advancement (`timer::work_elapsed`/`break_remaining`) —
	 *  only by an actual state transition, so idle ticking never looks dirty
	 *  to the sync loop. `#[serde(default)]` keeps old saved run-state JSON
	 *  deserializable.
	 */
	updatedAt?: number | null,
};

export type Session = {
	id: string,
	taskId: string,
	start: number | null,
	/**  None while running */
	end: number | null,
	/**  ms epoch of last change — drives cross-device sync (last-write-wins). */
	updatedAt?: number | null,
};

export type SessionConfig = {
	/**  "open" | "target" | "pomodoro" */
	mode: string,
	targetMin: number,
	workMin: number,
	breakMin: number,
	/**
	 *  macOS system sound name (see `SOUND_OPTIONS` in main.rs) played when a
	 *  work block ends and a break is ready to start. `#[serde(default)]`
	 *  keeps configs saved before this field existed deserializable.
	 */
	breakSound?: string,
	/**
	 *  Same as `break_sound`, played when a break ends and work is ready to
	 *  resume.
	 */
	workSound?: string,
	/**
	 *  Number of completed work cycles that earns a long break (Cirillo's
	 *  original technique: every 4th break is longer). `#[serde(default)]`
	 *  keeps configs saved before this field existed deserializable.
	 */
	cyclesBeforeLongBreak?: number,
	/**
	 *  Length of that long break, in minutes (editable 1–60, same range as
	 *  `break_min`).
	 */
	longBreakMin?: number,
	/**
	 *  Open mode only: fire a gentle check-in notification at each full hour
	 *  of continuous work. Device-local preference — deliberately NOT part of
	 *  `RemoteConfig` in sync.rs (notifications only ever fire on the device
	 *  running the session, and the remote `config` table has no such
	 *  column); the pull side preserves the local value when applying a
	 *  remote config. `#[serde(default)]` keeps configs saved before this
	 *  field existed deserializable.
	 */
	hourlyNudge?: boolean,
	/**
	 *  ms epoch of last change — drives cross-device sync (last-write-wins),
	 *  same convention as `RunState::updated_at` (see docs/session-sync-design.md
	 *  for the pattern this reuses: a singleton `config` row per account,
	 *  pushed only when dirty). `#[serde(default)]` keeps configs saved
	 *  before this field existed deserializable, and defaulting to 0 means
	 *  an old locally-saved config is never mistaken for "newer" than
	 *  whatever's already on the server.
	 */
	updatedAt?: number | null,
};

export type Snapshot = {
	lists: TaskList[],
	lifeAreaPriorities?: LifeAreaPriority[],
	tasks: Task[],
	sessions: Session[],
	musicFavorites?: MusicFavorite[],
	userSettings?: UserSettings,
	config: SessionConfig,
	run: RunState,
	/**
	 *  This device's own stable id (`Db::get_device_id()`) — the frontend
	 *  compares this against `run.deviceId` to tell "my session" (full
	 *  player) from "mirroring another device's session" (read-only, see
	 *  docs/session-sync-design.md). Not secret — same trust level as a
	 *  hostname.
	 */
	deviceId: string,
	account: AccountInfo | null,
	/**
	 *  true while a background sync push/pull is in flight. Lives here
	 *  (not in the lightweight `Status`/`tick` event) because the frontend
	 *  only ever listens to `state-changed` today, and sync is infrequent
	 *  enough (60s) that a full Snapshot rebuild per transition is cheap.
	 */
	syncing: boolean,
	/**  ms epoch of the last successful sync, if any */
	lastSyncedAt: number | null,
	/**
	 *  Error message from the most recent sync attempt, if it failed. Cleared
	 *  as soon as a later attempt succeeds. Lets the Settings UI distinguish
	 *  "actually synced" from "silently failing every cycle" instead of both
	 *  looking identical.
	 */
	lastSyncError: string | null,
	/**
	 *  App version (from Cargo.toml at compile time via env!("CARGO_PKG_VERSION")
	 *  in main.rs) — the Settings "About" section reads this instead of a
	 *  hardcoded string, so it can never drift out of sync with a real release
	 *  the way a hand-typed version number in the UI can.
	 */
	appVersion: string,
};

export type Task = {
	id: string,
	listId: string,
	name: string,
	/**  "deep" | "shallow" | null */
	depth: string | null,
	order: number,
	/**  Estimated effort in minutes (user enters hours). None = no estimate. */
	estimateMin?: number | null,
	/**
	 *  Freeform album/grouping name — related tasks within one list can share
	 *  an album, the way songs by one artist group into albums. None = a
	 *  "single" (shown in its own unlabeled section in the UI).
	 */
	album?: string | null,
	/**  When the task was marked complete (ms epoch). None = still to-do. */
	completedAt?: number | null,
	/**  Free-text description (shown as "lyrics" in the UI). None = none. */
	description?: string | null,
	/**  ms epoch of last change — drives cross-device sync (last-write-wins). */
	updatedAt?: number | null,
	/**
	 *  "low" | "medium" | "high" | None. Independent of
	 *  `estimate_min` on purpose — a 5-minute task can be `high` and a
	 *  2-hour one `low`; this (not duration) is what the frontend weighs
	 *  jewel payout and the life-balance radar contribution by. None = not
	 *  yet set, treated as weightless (no jewels either way) rather than
	 *  guessing a tier on the user's behalf. `#[serde(default)]` keeps tasks
	 *  saved before this field existed deserializable.
	 */
	impactTier?: string | null,
	/**
	 *  1 = counts FOR its list's tagged life area, -1 = AGAINST it (the
	 *  "smoked a cigarette" case — outsized, but negative). Local-only for now,
	 *  same as `TaskList::life_area`/`life_direction` (see the comment on
	 *  those) — not yet part of the Supabase remote schema.
	 */
	impactSign?: number,
	/**
	 *  Optional deadline (ms epoch, date granularity — always midnight local
	 *  time of the chosen day). None = no deadline. Independent of
	 *  `estimate_min` (a deadline is *when*, an estimate is *how long*) and
	 *  of `impact_tier` (a task can carry either without the other) — the
	 *  Home page's "Now" section (see docs/homepage-now-spec.md) only
	 *  surfaces a task once it has BOTH a deadline and `impact_tier` of at
	 *  least medium. `#[serde(default)]` keeps tasks saved before this field
	 *  existed deserializable.
	 */
	deadlineAt?: number | null,
	/**
	 *  None = one-time task (default; `completed_at` is the terminal
	 *  "done" state, jewelPayout counts once on that date). `Some("daily")`
	 *  = repeating — there is no terminal completion, "done" is derived
	 *  per calendar day from whether a session exists that day (see
	 *  render.js's `dailyPayoutOn`/`dailyPayoutDayCount`), and the jewel
	 *  pays out at most once per qualifying day rather than once ever.
	 *  Deliberately just an enum string, not a richer schedule (custom
	 *  weekdays, intervals, etc.) — matches the "don't build more machinery
	 *  than the one idea is worth" precedent set by `impact_tier`/`deadline_at`.
	 *  `#[serde(default)]` keeps tasks saved before this field existed
	 *  deserializable.
	 */
	cadence?: string | null,
	/**
	 *  Fixed local-time occurrences for a daily task. Ignored for one-time
	 *  tasks. Empty keeps a daily unscheduled rather than guessing a time.
	 */
	dailyWindows?: WeeklyTimeWindow[],
	/**
	 *  Smallest/largest useful planner block for a one-time task, in minutes.
	 *  Both are optional so existing tasks remain valid and can continue to
	 *  run without participating in automatic scheduling.
	 */
	minSessionMin?: number | null,
	maxSessionMin?: number | null,
};

export type TaskList = {
	id: string,
	name: string,
	emoji: string,
	color: string,
	order: number,
	/**  ms epoch of last change — drives cross-device sync (last-write-wins). */
	updatedAt?: number | null,
	/**
	 *  Life-balance area this list's tracked time counts toward (see the
	 *  Home page's radar chart) — one of "career" | "health" |
	 *  "relationships" | "finance" | "recreation". The retired "wellbeing"
	 *  and "growth" values are accepted from older clients and folded into
	 *  "health" (see migrations 010 and 015), or None leaves a list out of the
	 *  chart. `#[serde(default)]` keeps older lists deserializable.
	 */
	lifeArea?: string | null,
	/**
	 *  "increase" | "decrease" — whether time spent in this list should
	 *  count FOR or AGAINST its tagged `life_area` (e.g. a "Doomscrolling"
	 *  list tagged decrease:health pulls that axis down instead of up).
	 *  Meaningless when `life_area` is None. `#[serde(default)]` keeps
	 *  lists saved before this field existed deserializable.
	 */
	lifeDirection?: string | null,
	/**
	 *  Weekly local-time windows in which tasks belonging to this list may
	 *  be planned. Empty means the list has no scheduling constraint yet,
	 *  preserving the behavior of every list created before the planner.
	 */
	availabilityWindows?: WeeklyTimeWindow[],
};

export type UpdateInfo = {
	version: string,
	notes: string | null,
};

/**
 *  Cross-device preferences that are not part of timer/session configuration.
 *  The singleton row is last-write-wins, matching `SessionConfig`.
 */
export type UserSettings = {
	pauseForOtherAudio?: boolean,
	takeOverAppleMusic?: boolean,
	takeOverMusicPlayers?: boolean,
	updatedAt?: number | null,
};

/**
 *  A recurring local-time window within a week. `weekday` follows ISO-8601
 *  numbering (Monday = 1, Sunday = 7); start/end are minutes after local
 *  midnight and describe a half-open interval `[start_minute, end_minute)`.
 *  When `end_minute < start_minute`, the interval ends on the following day;
 *  equal start/end values are rejected by the editor as ambiguous.
 * 
 *  The planner will validate ranges before saving them. Keeping this as a
 *  shared value object lets lists describe when their context is available
 *  and daily tasks describe when each occurrence happens without inventing
 *  separate time formats for the two features.
 */
export type WeeklyTimeWindow = {
	weekday: number,
	startMinute: number,
	endMinute: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

